### ISSUE TITLE
[8.0] product multi company - question

### ISSUE THREAD

**Issue by laetitia-gangloff** [OCA/multi-company#21]
Hello,

why company_id is not a related on company_ids ? (is it possible ?!)
And, why in the case there is many companies define on the product, company_id is set with the first value ?

Last question, why record rules is set with in and not child_of ?

Thank you

**Comment by lmignon** [comment]
@laetitia-gangloff

> why company_id is not a related on company_ids ? (is it possible ?!) 

It's not possible and has no sens. Which company can we use if the user has access to a lot of them?

> And, why in the case there is many companies define on the product, company_id is set with the first value ?

 IMO, the company_id should be empty and never used once this module is installed otherwise we will encounter bugs. (IMO it's a bug)

> Last question, why record rules is set with in and not child_of ?

IMO to be consistent with others multi company record rules, we should use `child_of`

**Comment by pedrobaeza** [comment]
`company_id` is an standard Odoo field, so we should keep a value in it for possible modules that tries to acces that field. I decided to use the first record of the allowed companies. I could put a related field, because Odoo makes the same behaviour when relating a many2many in a many2one field, but I preferred to use a computed method that can be inherited is someone has another need/requirement instead of using the first record. The same applies to be empty instead of this. Any of the behaviors seems good for me.

About the record rule, I say no. This is put this way intentionally, because we will lose functionality using `child_of` operator. What if we want to give permission to the parent company and only one of the child ones? As this is a many2many, you can select all the companies you want. If you want to mimic the child_of behavior, select the parent and all of the children companies in it.

**Comment by laetitia-gangloff** [comment]
Thank you for your answers.
