### ISSUE TITLE
12.0 account_invoice_inter_company, unproper behavior of company_share_product = False

### ISSUE THREAD

**Issue by bealdav** [OCA/multi-company#242]
## What's wrong

In v12 we have this code and an equivalent in v11
https://github.com/OCA/multi-company/blob/12.0/account_invoice_inter_company/models/account_invoice.py#L232-L234

Analysis: 
`if dest_company.company_share_product is True` : whatever company_id field, all products are shared (weird odoo settings https://github.com/odoo/odoo/blob/12.0/addons/product/models/res_config_settings.py#L10)

`if dest_company.company_share_product is False` : we return self.env['product.product'] aka False whatever security rule

IMHO in this case it's completely wrong: it should depends on `product.product_comp_rule` security rule (['|',('company_id','=',user.company_id.id),('company_id','=',False)])

If product pass the rule, product_id must be used not instead of False

I'm in fault because I ported the module to v12

Are you ok with me ?

## How it could be better

Apply security rule

PR ...

cc @pedrobaeza @astirpe @florian-dacosta @sebastienbeau  Please confirm if I'm OK or not

**Comment by astirpe** [comment]
About this point I already expressed some doubts in https://github.com/OCA/multi-company/pull/119/files#r269030308. The fact is that at the moment there's no easy way for a user to configure the shared products, since the configuration of the shared products is made automatic, based on a security rule (active or inactive).

More in details, my doubts are basically on two points:

1. There's no easy/clear way to configure shared products, since standard `company_share_product` is overridden. Notice that the old version of the module had the `use_inter_company_products` feature. It was a very basic functionality but at least it was something usable.
2. The standard security rules for products could be in theory changed/customized by users. So if you want to base your solution on security rules, you should somehow take in consideration this fact.

Any improvement of these two points are very welcome :+1:

**Comment by bealdav** [comment]
Thanks @astirpe I understand your ideas for improvements but in my particular case I pointed a bug ;-)

**Comment by astirpe** [comment]
For our customers we need something more usable/configurable. Previous version of the module worked just fine.
Since I don't find particular benefits in those automatic behaviors based on security rule, let's wait for other opinions...

**Comment by florian-dacosta** [comment]
Hi,
Indeed, the present behavior is a bit hard.
I have only one project using this module in v12 and I checked, I had to override the behavior because I have a product multi company rule and still I share the catalog in a lot of cases...
So, the present behavior does not work for me neither and I am in favor on a change.
Like @astirpe the previous behavior was better for me

**Comment by bealdav** [comment]
> So, the present behavior does not work for me neither

ok

**Comment by bealdav** [comment]
On my side I don't like when customers update rules with no data file. So a matter of taste
