### ISSUE TITLE
Permission rule not applied using base_multi_company module

### ISSUE THREAD

**Issue by angedras** [OCA/multi-company#44]
Hi,
I have a problem with the module base_multi_company, I started the migration of module stock_production_lot_multi_company that inherit the base module (WIP [here](https://github.com/angedras/multi-company/tree/10.0-mig-stock_production_lot_multi_company))
I apply a rule to prevent the user to create or read lot data of other companies (security/stock_production_lot_security.xml) but the rule is not working as expected, the user is able to create lots for other companies and can also read these records after creation (test_03_error_lot_creation assertRaises fails).

Have i misunderstood the usage of the module (i.e. the reference to 'res.company.assignment' model in the abstract class ('multi.company.abstract'))?

Thanks
cc @pedrobaeza @lasley

**Comment by lasley** [comment]
Hi @angedras - Nope you haven't misunderstood the module purpose, and it looks like you've implemented the inheritance correctly. Honestly I don't think I considered security rules when I was making the base, because they don't seem to be implemented in any of the edge modules.

@pedrobaeza - am I missing something? I feel like I saw security somewhere, but I'm not seeing them in the v9s.

**Comment by lasley** [comment]
@angedras - I believe the solution to your issue is that you instead want to use a hook to override the pre-existing security. Take a look [here](https://github.com/LasLabs/multi-company/blob/76733358dd329e1eed07f9c1bb8f2a6bc464fb49/product_template_multi_company/hooks.py)
